spring:
  application:
    name: ${WEB_APPLICATION_NAME}
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${WEB_DATASOURCE_URL}
    username: ${WEB_DATASOURCE_USERNAME}
    password: ${WEB_DATASOURCE_PASSWORD}
    driver-class-name: ${WEB_DATASOURCE_DRIVER_CLASS_NAME}

server:
  port: ${WEB_SERVER_PORT}

sms:
  web:
    jwt:
      secret: ${JWT_SECRET}
      access-token-ttl-seconds: ${JWT_ACCESS_TOKEN_TTL_SECONDS}
      refresh-token-ttl-seconds: ${JWT_REFRESH_TOKEN_TTL_SECONDS}
