-- PostgreSQL/pgvector schema for the default sms-knowledge vector backend.
-- Override it with KNOWLEDGE_VECTOR_STORE=milvus when using Milvus.
CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS ai_knowledge_chunk (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(64) NOT NULL,
    knowledge_base_id BIGINT NOT NULL,
    document_id BIGINT NOT NULL,
    document_no VARCHAR(128) NOT NULL,
    document_version_id BIGINT NOT NULL,
    index_revision INTEGER NOT NULL DEFAULT 1,
    chunk_no INTEGER NOT NULL,
    content TEXT NOT NULL,
    metadata JSONB,
    embedding VECTOR(1536) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    create_by VARCHAR(64),
    modify_by VARCHAR(64),
    create_time TIMESTAMP,
    update_time TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_ai_knowledge_chunk_tenant_base_status
    ON ai_knowledge_chunk (tenant_id, knowledge_base_id, status);

CREATE UNIQUE INDEX IF NOT EXISTS uk_ai_knowledge_chunk_document
    ON ai_knowledge_chunk
    (tenant_id, knowledge_base_id, document_id, document_version_id, index_revision, chunk_no);

-- Add an ivfflat index after data has been loaded and the embedding dimension is known.
-- CREATE INDEX idx_ai_knowledge_chunk_embedding ON ai_knowledge_chunk
-- USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);
