spring:
  application:
    name: sms-ai
  config:
    import: optional:nacos:127.0.0.1:8848

dubbo:
  application:
    name: sms-ai-consumer
  registry:
    address: nacos://127.0.0.1:8848

server:
  port: 9091


langchain4j:
  open-ai:
    chat-model:
      base-url: http://langchain4j.dev/demo/openai/v1
      api-key: demo
      model-name: gpt-4o-mini
    streaming-chat-model:
      api-key: demo
      model-name: gpt-4o-mini