spring:
  application:
    name: sms-ai
  config:
    import: optional:nacos:127.0.0.1:8848

dubbo:
  application:
    name: sms-ai-consumer
  registry:
    address: nacos://127.0.0.1:8848

server:
  port: 9091


langchain4j:
  open-ai:
    chat-model:
      base-url: https://blankapi.com/v1
      api-key: sk-SMwjAMd8gTKchw2tWRGS9dau3Tat6tKIMp8sownxeCL6qqRU
      model-name: gpt-5.6-terra
    streaming-chat-model:
      api-key: demo
      model-name: gpt-4o-mini